name: mirror_dispatcher
description: Method Dispatcher using dart:mirrors
version: 1.0.0
repository: https://github.com/jwashin/mirror_dispatcher

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rpc_dispatcher: ^1.0.0
  rpc_exceptions: any

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
